name: pizzeria_challenge
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  get: ^3.25.6
  http: ^0.12.2
  cached_network_image: ^2.5.0
  firebase_core: ^0.7.0
  connectivity: ^2.0.2
  image_picker: ^0.6.7+22
  permission_handler: ^5.1.0+2
  firebase_database: ^6.0.0
  location: 3.0.2
  location_permissions: ^3.0.0+1
  google_maps_flutter: ^0.5.25
  firebase_storage: ^7.0.0
  google_sign_in: ^4.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/
